openapi: 3.0.0
info:
  title: Customer API
  description: This is a simple API
  contact:
    email: shree@gmail.com
  version: 2.0.0
servers:
- url: https://virtserver.swaggerhub.com/hplusApi/Customer_API/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Customer API
  description: simple customer API
paths:
  /customer:
    get:
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customers'
        "400":
          description: bad input parameter
    post:
      description: Adding an new customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customers'
      responses:
        "201":
          description: Customer added
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      security:
      - password:
        - write
  /customer/{customerId}:
    get:
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: customer details is
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customers'
    put:
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: customer details updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      security:
      - password:
        - write
    delete:
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 1
      responses:
        "204":
          description: Customer is deleted -- No content to display
      security:
      - password:
        - write
components:
  schemas:
    customers:
      required:
      - city
      - firstName
      - id
      - lastName
      - phone
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: shree
        lastName:
          type: string
          example: J
        phone:
          type: string
          example: 111-222-3333
        city:
          type: string
          example: toronto
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: j
        lastName:
          type: string
          example: shree
        phone:
          type: string
          example: 100-000-0101
        city:
          type: string
          example: ottawa
  parameters:
    customerId:
      name: customerId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: integer
        example: 1
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: http://example.com/oauth/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
